name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      ## Checkout current branch
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --check-files
      - name: Build code
        run: yarn build

      - name: Set target
        id: set-target
        run: |
          if [[ ${{ github.ref }} == refs/heads/main ]]; then
            echo "::set-output name=target::$(echo main)"
          else
            echo "::set-output name=target::$(echo develop)"
          fi

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESIS_99BA6 }}"
          channelId: live
          projectId: tesis-99ba6
          target: "${{steps.set-target.target}}"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
