name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15"

      - name: Install dependencies
        run: yarn install --check-files
      - name: Build code
        run: yarn build

      # Artifacts
      - name: Upload code artifact
        uses: actions/upload-artifact@v2
        with:
          name: react_build
          path: build
      - uses: actions/upload-artifact@v2
        with:
          name: .firebaserc
          path: ./.firebaserc
      - uses: actions/upload-artifact@v2
        with:
          name: firebase.json
          path: ./firebase.json

  deploy_develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: ${{steps.deploy.urls}}
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      # Download artifacts from build job
      - name: Download react build
        uses: actions/download-artifact@v2
        with:
          name: react_build
          path: build
      - name: Download Firebase config
        uses: actions/download-artifact@v2
        with:
          name: .firebaserc
      - name: Download Firebase config
        uses: actions/download-artifact@v2
        with:
          name: firebase.json

      # Deploy
      - name: Deploy
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESIS_99BA6 }}"
          channelId: live
          projectId: tesis-99ba6
          target: develop
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  deploy_main:
    runs-on: ubuntu-latest
    environment:
      name: main
      url: ${{steps.deploy.urls}}
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      # Download artifacts from build job
      - name: Download react build
        uses: actions/download-artifact@v2
        with:
          name: react_build
          path: build
      - name: Download Firebase config
        uses: actions/download-artifact@v2
        with:
          name: .firebaserc
      - name: Download Firebase config
        uses: actions/download-artifact@v2
        with:
          name: firebase.json

      # Deploy
      - name: Deploy
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESIS_99BA6 }}"
          channelId: live
          projectId: tesis-99ba6
          target: main
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
